#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fdk-aac
Version  : 2.0.1
Release  : 1
URL      : https://github.com/mstorsjo/fdk-aac/archive/v2.0.1.tar.gz
Source0  : https://github.com/mstorsjo/fdk-aac/archive/v2.0.1.tar.gz
Summary  : AAC codec library
Group    : Development/Tools
License  : BSD-2-Clause
Requires: fdk-aac-lib = %{version}-%{release}

%description
No detailed description available

%package dev
Summary: dev components for the fdk-aac package.
Group: Development
Requires: fdk-aac-lib = %{version}-%{release}
Provides: fdk-aac-devel = %{version}-%{release}
Requires: fdk-aac = %{version}-%{release}

%description dev
dev components for the fdk-aac package.


%package lib
Summary: lib components for the fdk-aac package.
Group: Libraries

%description lib
lib components for the fdk-aac package.


%prep
%setup -q -n fdk-aac-2.0.1
cd %{_builddir}/fdk-aac-2.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586632744
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static --enable-shared
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1586632744
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/fdk-aac/FDK_audio.h
/usr/include/fdk-aac/aacdecoder_lib.h
/usr/include/fdk-aac/aacenc_lib.h
/usr/include/fdk-aac/genericStds.h
/usr/include/fdk-aac/machine_type.h
/usr/include/fdk-aac/syslib_channelMapDescr.h
/usr/lib64/libfdk-aac.so
/usr/lib64/pkgconfig/fdk-aac.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfdk-aac.so.2
/usr/lib64/libfdk-aac.so.2.0.1
